### ISSUE TITLE
[BUG]: createNodeMiddleware is not exported (via esm.sh)

### ISSUE THREAD

**Issue by denizdogan** [octokit/oauth-app.js#424] opened 2023-06-12 12:55 UTC
### What happened?

Originally commented here: https://github.com/octokit/octokit.js/issues/2450#issuecomment-1587033216

Importing `https://esm.sh/octokit` fails, at least in Deno 1.34.2, because it cannot see the `createNodeMiddleware` export. I think this is due to something in #416 because overriding the dependency to use 4.2.1 works fine.

```console
❯ cat foobar.ts
import { App } from "https://esm.sh/octokit"; console.log(App);

❯ deno run --unstable -A --no-lock --reload foobar.ts
error: Uncaught SyntaxError: The requested module '/v125/@octokit/oauth-app@4.2.2/denonext/oauth-app.mjs' does not provide an export named 'createNodeMiddleware'
    at <anonymous> (https://esm.sh/v125/@octokit/app@13.1.5/denonext/app.mjs:2:842)
```

### Versions

Failing version: `https://esm.sh/octokit@2.0.19`

Working version: `https://esm.sh/octokit@2.0.19?dts&target=deno&deps=@octokit/oauth-app@4.2.1`

```
❯ deno --version
deno 1.34.2 (release, aarch64-apple-darwin)
v8 11.5.150.2
typescript 5.0.4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment] 2023-06-12 17:14
I don't think this is something on our side. It looks to be a bug with eam.sh

**Comment by denizdogan** [comment] 2023-06-13 02:52
It might be esm.sh. I haven't been able to debug it very thoroughly, as I'm still a bit unfamiliar with the Octokit codebase. Another interesting thing I found was in these files:

https://esm.sh/v125/octokit@2.0.19/X-ZC9Ab2N0b2tpdC9vYXV0aC1hcHBANC4yLjE/dist-types/app.d.ts

https://esm.sh/v125/octokit@2.0.19/X-ZC9Ab2N0b2tpdC9vYXV0aC1hcHBANC4yLjE/dist-types/octokit.d.ts

Note where it says **types.d~.d.ts**... I have no idea where that came from. Just esm.sh being wonky again? It seems so random.

**Comment by wolfy1339** [comment] 2023-06-14 01:05
That is indeed a weird bug. However, it doesn't seem related to your issue though

**Comment by wolfy1339** [comment] 2023-06-14 21:50
Can you test if using the ESM source build works, you can load it from here: https://unpkg.com/octokit@2.0.19/dist-src/index.js

**Comment by denizdogan** [comment] 2023-06-14 23:17
@wolfy1339 Unfortunately it did not work, but nice try :) 

When Deno tries to load the URL, we get this:

```
❯ deno run --allow-net octokit-deno-testing.ts
error: Relative import path "@octokit/plugin-throttling" not prefixed with / or ./ or ../ and not in import map from "https://unpkg.com/octokit@2.0.19/dist-src/octokit.js"
    at https://unpkg.com/octokit@2.0.19/dist-src/octokit.js:5:28

❯ cat octokit-deno-testing.ts
import * as octokit from "https://unpkg.com/octokit@2.0.19/dist-src/index.js";
```

**Comment by wolfy1339** [comment] 2023-06-15 01:27
I wonder if this is just a deno problem.

Can you try downloading the contents of the `dist-src` folder and import it locally: https://unpkg.com/browse/@octokit/oauth-app@4.2.2/dist-src/

In the mean time, I have filed https://github.com/esm-dev/esm.sh/issues/659

**Comment by ije** [comment] 2023-06-15 11:30
will fix ASAP

**Comment by wolfy1339** [comment] 2023-06-15 14:08
@denizdogan Can you try again? This should be fixed in ESM.sh now

**Comment by denizdogan** [comment] 2023-06-15 14:45
@wolfy1339 That works! Thanks.

But I will add there's still this one weird little URL which is pointed at by `https://esm.sh/v126/octokit@2.0.19/dist-types/app.d.ts`:

- `https://esm.sh/v126/@octokit/core@4.2.1/dist-types/types.d~.d.ts`

Any ideas about that one? The code still runs, but some type information goes missing.

**Comment by ije** [comment] 2023-06-15 15:03
> @wolfy1339 That works! Thanks.
> 
> But I will add there's still this one weird little URL which is pointed at by `https://esm.sh/v126/octokit@2.0.19/dist-types/app.d.ts`:
> 
> * `https://esm.sh/v126/@octokit/core@4.2.1/dist-types/types.d~.d.ts`
> 
> Any ideas about that one? The code still runs, but some type information goes missing.

i just file a issue, will fix soon https://github.com/esm-dev/esm.sh/issues/660

**Comment by wolfy1339** [comment] 2023-06-20 00:33
Closing as the issue is fixed, and the subsequent problem with paths has an issue filed with esm.sh

**Closed by wolfy1339** 2023-06-20 00:33 UTC
Labels: Type: Bug, Priority: High
